apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug-container
    image: busybox
    command: ["/bin/sh", "-c", "sleep 10000"]
    volumeMounts:
    - name: geth-claim1
      mountPath: /usr/local/bin/
      subPath: usr/local/bin/
    - name: geth-claim1
      mountPath: /config/
      subPath: config/
  volumes:
  - name: geth-claim1
    persistentVolumeClaim:
      claimName: geth-claim1
