apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: geth
  name: geth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: geth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/eip4844-devnet-default: "true"
        io.kompose.service: geth
    spec:
      # initContainers:
      #   - name: init-script
      #     image: busybox
      #     command: 
      #       - sh
      #       - -c
      #       - |
      #         cp /config-map/geth.sh /usr/local/bin/ &&
      #         chmod 755 /usr/local/bin/geth.sh &&
      #         cp /config-map/jwtsecret /config/ &&
      #         cp /config-map/genesis.json /config/ &&
      #         cp /config-map/enodes.list /config/
      #     volumeMounts:
      #     - name: config-volume
      #       mountPath: /config-map
      containers:
        - command: ["/bin/sh", "-c"]
          args:
            - |
              cp /tmp/geth.sh /usr/local/bin/geth.sh &&
              chmod 755 /usr/local/bin/geth.sh &&
              /usr/local/bin/geth.sh
          env:
            - name: EL_P2P_PORT
              value: "30303"
          image: eip4844-devnet-geth:latest
          imagePullPolicy: Never
          name: geth
          ports:
            - containerPort: 8545
              hostPort: 8545
              protocol: TCP
            - containerPort: 30303
              hostIP: 0.0.0.0
              hostPort: 30303
              protocol: TCP
            - containerPort: 30303
              hostIP: 0.0.0.0
              hostPort: 30303
              protocol: UDP
          resources:
            requests:
                memory: "500Mi"
                cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
          volumeMounts:
            - mountPath: /db
              name: geth-data
            - name: config-volume
              mountPath: /tmp/geth.sh
              subPath: geth.sh
            - name: config-volume
              mountPath: /config/jwtsecret
              subPath: jwtsecret
            - name: config-volume
              mountPath: /config/genesis.json
              subPath: genesis.json
            - name: config-volume
              mountPath: /config/enodes.list
              subPath: enodes.list
      restartPolicy: Always
      volumes:
        - name: geth-data
          persistentVolumeClaim:
            claimName: geth-data
        - name: config-volume
          configMap:
            name: eip4844-devnet-config
status: {}
