apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: geth
  name: geth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: geth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/eip4844-devnet-default: "true"
        io.kompose.service: geth
    spec:
      initContainers:
        - name: init-script
          image: busybox
          command: 
            - sh
            - -c
            - |
              cp /config-map/geth.sh /usr/local/bin/ &&
              chmod 755 /usr/local/bin/geth.sh &&
              cp /config-map/jwtsecret /config/ &&
              cp /config-map/genesis.json /config/ &&
              cp /config-map/enodes.list /config/
          volumeMounts:
          - name: config-volume
            mountPath: /config-map
          - name: geth-claim1
            mountPath: /usr/local/bin/
            subPath: usr/local/bin/
          - name: geth-claim1
            mountPath: /config
            subPath: config
      containers:
        - args:
            - /usr/local/bin/geth.sh
          env:
            - name: EL_P2P_PORT
              value: "30303"
          image: eip4844-devnet-geth:latest
          imagePullPolicy: Never
          name: geth
          ports:
            - containerPort: 8545
              hostPort: 8545
              protocol: TCP
            - containerPort: 30303
              hostIP: 0.0.0.0
              hostPort: 30303
              protocol: TCP
            - containerPort: 30303
              hostIP: 0.0.0.0
              hostPort: 30303
              protocol: UDP
          resources:
            requests:
                memory: "500Mi"
                cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
          volumeMounts:
            - mountPath: /db
              name: geth-data
            - mountPath: /usr/local/bin/
              name: geth-claim1
              subPath: usr/local/bin/
            - mountPath: /config/
              name: geth-claim1
              subPath: config/
      restartPolicy: Always
      volumes:
        - name: geth-data
          persistentVolumeClaim:
            claimName: geth-data
        - name: geth-claim1
          persistentVolumeClaim:
            claimName: geth-claim1
        - name: config-volume
          configMap:
            name: eip4844-devnet-config
status: {}
