apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: lighthouse-container
  name: lighthouse-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lighthouse-container
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/eip4844-devnet-default: "true"
        io.kompose.service: lighthouse-container
    spec:
      # initContainers:
      # - name: init-copy
      #   image: busybox
      #   imagePullPolicy: IfNotPresent
      #   command: ['sh', '-c']
      #   args:
      #       - |
      #         mkdir -p /config/testnet &&
      #         cp -r /cl-config-volume/source /config/testnet
      #   volumeMounts:
      #     - name: cl-config-volume
      #       mountPath: /cl-config-volume/source
      containers:
        - command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /config &&
              cp -r /cl-config-volume/source /config/testnet &&
              cp /tmp/lighthouse.sh /usr/local/bin/lighthouse.sh &&
              chmod 755 /usr/local/bin/lighthouse.sh &&
              /usr/local/bin/lighthouse.sh
          env:
            # - name: CHECKPOINT_SYNC_URL
            #   value: https://dencun-devnet-12.ethpandaops.io/
            - name: CL_LOG_LEVEL
              value: info
            - name: EL_P2P_PORT
              value: "30303"
            - name: CL_P2P_PORT
              value: "9000"
            - name: GETH_PORT
              value: "8545"
            - name: HTTPS_PROXY
              value: "http://192.168.0.113:7890"
            - name: HTTP_PROXY
              value: "http://192.168.0.113:7890"
            - name: ALL_PROXY
              value: "socks5://192.168.0.113:7890"
            - name: NO_PROXY
              value: "localhost,127.0.0.1,10.*"

          image: eip4844-devnet-lighthouse:latest
          imagePullPolicy: Never
          name: lighthouse-container
          ports:
            - containerPort: 5052
              hostPort: 5052
              protocol: TCP
            - containerPort: 5054
              hostPort: 5054
              protocol: TCP
            - containerPort: 9000
              hostIP: 0.0.0.0
              hostPort: 9000
              protocol: TCP
            - containerPort: 9000
              hostIP: 0.0.0.0
              hostPort: 9000
              protocol: UDP
          resources:
            requests:
                memory: "500Mi"
                cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
          volumeMounts:
            - mountPath: /data
              name: lighthouse-container-data
            - name: config-volume
              mountPath: /tmp/lighthouse.sh
              subPath: lighthouse.sh
            - name: config-volume
              mountPath: /config/jwtsecret
              subPath: jwtsecret
            - name: config-volume
              mountPath: /config/genesis.json
              subPath: genesis.json
            - name: config-volume
              mountPath: /config/enodes.list
              subPath: enodes.list
            - name: cl-config-volume
              mountPath: /cl-config-volume/source
              # subPath: cl_config
      restartPolicy: Always
      volumes:
        - name: lighthouse-container-data
          persistentVolumeClaim:
            claimName: lighthouse-container-data
        - name: config-volume
          configMap:
            name: eip4844-devnet-config
        - name: cl-config-volume
          persistentVolumeClaim:
            claimName: cl-config-pvc
status: {}
