apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: lighthouse
  name: lighthouse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lighthouse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/eip4844-devnet-default: "true"
        io.kompose.service: lighthouse
    spec:
      containers:
        - args:
            - /usr/local/bin/lighthouse.sh
          env:
            - name: CHECKPOINT_SYNC_URL
            - name: CL_LOG_LEVEL
              value: info
            - name: CL_P2P_PORT
              value: "9000"
          image: lighthouse
          name: lighthouse
          ports:
            - containerPort: 5052
              hostPort: 5052
              protocol: TCP
            - containerPort: 5054
              hostPort: 5054
              protocol: TCP
            - containerPort: 9000
              hostIP: 0.0.0.0
              hostPort: 9000
              protocol: TCP
            - containerPort: 9000
              hostIP: 0.0.0.0
              hostPort: 9000
              protocol: UDP
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: lighthouse-data
            - mountPath: /usr/local/bin/lighthouse.sh
              name: lighthouse-claim1
            - mountPath: /config/testnet
              name: lighthouse-claim2
            - mountPath: /config/jwtsecret
              name: lighthouse-claim3
      restartPolicy: Always
      volumes:
        - name: lighthouse-data
          persistentVolumeClaim:
            claimName: lighthouse-data
        - name: lighthouse-claim1
          persistentVolumeClaim:
            claimName: lighthouse-claim1
        - name: lighthouse-claim2
          persistentVolumeClaim:
            claimName: lighthouse-claim2
        - name: lighthouse-claim3
          persistentVolumeClaim:
            claimName: lighthouse-claim3
status: {}
