apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: lighthouse
  name: lighthouse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lighthouse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/eip4844-devnet-default: "true"
        io.kompose.service: lighthouse
    spec:
      initContainers:
        - name: init-script
          image: busybox
          command: 
            - sh
            - -c
            - |
              cp /config-map/lighthouse.sh /usr/local/bin/ &&
              chmod 755 /usr/local/bin/lighthouse.sh
              cp /config-map/jwtsecret /config/ &&
              cp /config-map/genesis.json /config/ &&
              cp /config-map/enodes.list /config/
          volumeMounts:
          - name: config-volume
            mountPath: /config-map
          - name: geth-claim1
            mountPath: /usr/local/bin/
            subPath: usr/local/bin/
          - name: geth-claim1
            mountPath: /config
            subPath: config
      containers:
        - args:
            - /usr/local/bin/lighthouse.sh
          env:
            - name: CHECKPOINT_SYNC_URL
            - name: CL_LOG_LEVEL
              value: info
            - name: CL_P2P_PORT
              value: "9000"
          image: eip4844-devnet-lighthouse:latest
          imagePullPolicy: Never
          name: lighthouse
          ports:
            - containerPort: 5052
              hostPort: 5052
              protocol: TCP
            - containerPort: 5054
              hostPort: 5054
              protocol: TCP
            - containerPort: 9000
              hostIP: 0.0.0.0
              hostPort: 9000
              protocol: TCP
            - containerPort: 9000
              hostIP: 0.0.0.0
              hostPort: 9000
              protocol: UDP
          resources:
            requests:
                memory: "500Mi"
                cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
          volumeMounts:
            - mountPath: /data
              name: lighthouse-data
            - mountPath: /usr/local/bin/
              name: geth-claim1
              subPath: usr/local/bin/
            - mountPath: /config/
              name: geth-claim1
      restartPolicy: Always
      volumes:
        - name: lighthouse-data
          persistentVolumeClaim:
            claimName: lighthouse-data
        - name: geth-claim1
          persistentVolumeClaim:
            claimName: geth-claim1
        - name: config-volume
          configMap:
            name: eip4844-devnet-config
status: {}
